# Generated by Django 4.2.7 on 2024-04-16 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.PositiveIntegerField(verbose_name='Номер счета')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='День рождения')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('status', models.CharField(choices=[('Не в работе', 'Не в работе'), ('В работе', 'В работе'), ('Отказ', 'Отказ'), ('Сделка закрыта', 'Сделка закрыта')], default='Не в работе', max_length=100, verbose_name='Статус')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Список клиентов',
            },
        ),
    ]
