# Generated by Django 4.2.7 on 2024-04-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Не в работе', 'Не в работе'), ('В работе', 'В работе'), ('Отказ', 'Отказ'), ('Сделка закрыта', 'Сделка закрыта')], default='Не в работе', max_length=100),
        ),
    ]
